# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       libevent

# >> macros
# << macros

Summary:    Library to execute a function when a specific event occurs on a file descriptor
Version:    2.1.12
Release:    1
Group:      Development/Libraries
License:    BSD-3-Clause
URL:        https://libevent.org
Source0:    %{name}-%{version}.tar.gz
Source100:  libevent.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libssl)
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool

%description
%{summary}.

%if "%{?vendor}" == "chum"
Categories:
 - Library
Custom:
  PackagingRepo: https://github.com/sailfishos-chum/libevent
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
./autogen.sh
# << build pre

%configure --disable-static \
    --with-gnu-ld \
    --disable-libevent-regress \
    --disable-doxygen-html

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_libdir}/*.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
# >> files devel
# << files devel
